// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0KrSlZcAt-NGAGWC0KfFYJjTwlbB0F0A',
    appId: '1:446018190878:web:0ec8a3b3c04acbec99380f',
    messagingSenderId: '446018190878',
    projectId: 'sedya-c27aa',
    authDomain: 'sedya-c27aa.firebaseapp.com',
    storageBucket: 'sedya-c27aa.firebasestorage.app',
    measurementId: 'G-EVNVDX4H4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZqSJYEI5E0SNSz-CVEMhGFPQVQWS-6FI',
    appId: '1:446018190878:android:a8dd0e7e660be40699380f',
    messagingSenderId: '446018190878',
    projectId: 'sedya-c27aa',
    storageBucket: 'sedya-c27aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgV-NEk5X2zqfP_NVgriLCOpkMjKBnenM',
    appId: '1:446018190878:ios:ba06a66eec9255c699380f',
    messagingSenderId: '446018190878',
    projectId: 'sedya-c27aa',
    storageBucket: 'sedya-c27aa.firebasestorage.app',
    iosClientId: '446018190878-nhq0rjsifl11t44p8ma0t9g04jgtuhq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.sedyaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgV-NEk5X2zqfP_NVgriLCOpkMjKBnenM',
    appId: '1:446018190878:ios:ba06a66eec9255c699380f',
    messagingSenderId: '446018190878',
    projectId: 'sedya-c27aa',
    storageBucket: 'sedya-c27aa.firebasestorage.app',
    iosClientId: '446018190878-nhq0rjsifl11t44p8ma0t9g04jgtuhq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.sedyaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0KrSlZcAt-NGAGWC0KfFYJjTwlbB0F0A',
    appId: '1:446018190878:web:e2513206ca6e37fc99380f',
    messagingSenderId: '446018190878',
    projectId: 'sedya-c27aa',
    authDomain: 'sedya-c27aa.firebaseapp.com',
    storageBucket: 'sedya-c27aa.firebasestorage.app',
    measurementId: 'G-R35L7H3DCR',
  );
}
